language: node_js
node_js:
  - "10"
  - "9"
  - "8"
  - "7"
  - "6"
  - "5"
install:
  - npm i -g node-gyp gulp
script:
  - npm run build-addon
  - npm run build
  - npm run lint
  - npm run test-coverage
  - npm run coveralls