language: node_js
node_js:
  - "10"
  - "9"
  - "8"
  - "7"
  - "6"
os:
  - linux
  - osx
branches:
  only:
    - master
cache:
  directories:
    - ".eslintcache"
    - "node_modules"
install:
  - npm i
  - npm i -g node-gyp
script:
  - npm run build-addon
  - npm run build
  - npm run lint
  - npm run flow-typed:install
  - npm run typecheck
  - npm run test-coverage
  - npm run coveralls
before_deploy:
  - git tag "$(node -p "require('./package.json').version").$TRAVIS_BUILD_NUMBER"
deploy:
  - provider: npm
    email: $NPM_EMAIL
    api_key: $NPM_AUTH_TOKEN
    skip_cleanup: true
    on:
      branch: master
  - provider: releases
    api_key: $GITHUB_OAUTH_TOKEN
    file: $TRAVIS_BUILD_DIR
    skip_cleanup: true