const Scope = require('./src').default
const filename = require.resolve('./test/dummy/newGlobalScope')
const NewGlobalScope = Scope.New(filename, {})
const newGlobalScope = new NewGlobalScope()
let value = newGlobalScope.getGlobal('test')
console.log(value)
newGlobalScope.setGlobal('test', 'aaaa')
value = newGlobalScope.getGlobal('test')
console.log(value)
const NewGlobalScope2 = Scope.New(filename, {})
const newGlobalScope2 = new NewGlobalScope2()
value = newGlobalScope2.getGlobal('test')
console.log(value)
newGlobalScope2.setGlobal('test', 'bbbb')
value = newGlobalScope2.getGlobal('test')
console.log(value)
