// flow-typed signature: d41cd9035faede7fa94869b5f2711e6f
// flow-typed version: <<STUB>>/gulp-run-command_v0.0.9/flow_v0.74.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'gulp-run-command'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'gulp-run-command' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'gulp-run-command/index.es5' {
  declare module.exports: any;
}

// Filename aliases
declare module 'gulp-run-command/index.es5.js' {
  declare module.exports: $Exports<'gulp-run-command/index.es5'>;
}
declare module 'gulp-run-command/index' {
  declare module.exports: $Exports<'gulp-run-command'>;
}
declare module 'gulp-run-command/index.js' {
  declare module.exports: $Exports<'gulp-run-command'>;
}
