// flow-typed signature: 50891277b96f88128aa44827bcd2e7fb
// flow-typed version: <<STUB>>/gulp-prompt_v^1.0.1/flow_v0.74.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'gulp-prompt'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'gulp-prompt' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'gulp-prompt/examples/chain-confirm-gulpfile' {
  declare module.exports: any;
}

declare module 'gulp-prompt/examples/first-choice-selection-gulpfile' {
  declare module.exports: any;
}

declare module 'gulp-prompt/examples/list-selection-gulpfile' {
  declare module.exports: any;
}

declare module 'gulp-prompt/examples/template-replacement-gulpfile' {
  declare module.exports: any;
}

// Filename aliases
declare module 'gulp-prompt/examples/chain-confirm-gulpfile.js' {
  declare module.exports: $Exports<'gulp-prompt/examples/chain-confirm-gulpfile'>;
}
declare module 'gulp-prompt/examples/first-choice-selection-gulpfile.js' {
  declare module.exports: $Exports<'gulp-prompt/examples/first-choice-selection-gulpfile'>;
}
declare module 'gulp-prompt/examples/list-selection-gulpfile.js' {
  declare module.exports: $Exports<'gulp-prompt/examples/list-selection-gulpfile'>;
}
declare module 'gulp-prompt/examples/template-replacement-gulpfile.js' {
  declare module.exports: $Exports<'gulp-prompt/examples/template-replacement-gulpfile'>;
}
declare module 'gulp-prompt/index' {
  declare module.exports: $Exports<'gulp-prompt'>;
}
declare module 'gulp-prompt/index.js' {
  declare module.exports: $Exports<'gulp-prompt'>;
}
